server:
  port: 0
  
spring:
  application:
    name: stud-kafkaconsumerservice
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      id:
        new_generator_mappings: false  
  
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
kafka:
  bootstrapAddress: localhost:9092
  
general:
  topic:
    name: test-log
    group-id: group_id
    
stud:
  topic:
    name: stud-log
    group-id: group-id
    
emp:
  topic:
    name: emptest
    group-id: group-id

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
  service-url:
    defaultzone: http://localhost:8761/eureka/    
    
